eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://ec2-3-236-107-207.compute-1.amazonaws.com:8761/eureka/
  instance:
    hostname: ec2-3-236-107-207.compute-1.amazonaws.com
